config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
	resources :games,      only: [:index, :show]
  resources :developers, only: [:index, :show]
  resources :genres,     only: [:index, :show]
  resources :abouts,     only: [:index, :show]
  resources :contacts,   only: [:index, :show]
  
  get 'search_results' => 'games#search_results', as: 'search_results'
  
  get 'abouts/index'
  get 'contacts/index'

  get 'genres/index'
  get 'genres/show'

  get 'developers/index'
  get 'developers/show'

  get 'games/index'
  get 'games/show'

  get 'home/index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders,
           dependent: :destroy
  belongs_to :province

  validates :first_name,
            :last_name,
            :address,
            :city,
            :postal_code,
            :country,
            presence: true
  validates :credit_card_number,
            :credit_card_expiry_date,
            numericality: true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games,
           dependent: :destroy

  validates :name,
            presence: true
  validates :name,
            uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :orders,
           dependent: :destroy
  belongs_to :developer
  belongs_to :genre

  validates :title,
            :stock_quantity,
            :price,
            presence: true
  validates :price,
            :stock_quantity,
            numericality: true
  validates :title,
            uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games,
           dependent: :destroy

  validates :name,
            presence: true
  validates :name,
            uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :games,
           dependent: :destroy
  belongs_to :customer

  validates :quantity,
            :total_price,
            numericality: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers,
           dependent: :destroy

  validates :name,
            presence: true
  validates :pst_rate,
            :gst_rate,
            :hst_rate,
            numericality: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.first
  end
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  def index
    @developers = Developer.all
  end

  def show
    @developers = Developer.includes(:games)
                           .where(id: params[:id])
                           .order('games.release_date DESC')
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.order(:title)
  end

  def show
    @game = Game.find(params[:id])
  end

  def search_results
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    genre_selection = params[:genre_id]

    if genre_selection.size.zero?
      @games = Game.where('title LIKE ?',
                          wildcard_keywords)
    else
      @games = Game.where('title LIKE ? AND genre_id = ?',
                          wildcard_keywords,
                          genre_selection)
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all.order(:name)
  end

  def show
    @genres = Genre.includes(:games)
                   .where(id: params[:id])
                   .order('games.release_date DESC')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.order(:title)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/abouts/index.html.erb
<h1>About Us</h1>
<p><%= @about.text %></p>

app/views/contacts/index.html.erb
<h1>Contact Us</h1>
<p><%= @contact.text %></p>

app/views/developers/index.html.erb
<h1>Developers</h1>
<% @developers.each do |developer| %>
  <h2><%= developer.name %></h2>
  <%= link_to 'Details', developer %>
<% end %>

app/views/developers/show.html.erb
<h1>Developers</h1>
<% @developers.each do |developer| %>
  <h2><%= developer.name %></h2>
  <% developer.games.each do |game| %>
    <h3><%= game.title %></h3>
    <p><a href="/games/<%= game.id %>"><%= image_tag game.image_url %></a></p>
  <% end %>
<% end %>
<%= link_to 'Back', developers_path %>

app/views/games/_game.html.erb
<h2><%= game.title %></h2>
<p><%= image_tag game.image_url %></p>
<p><strong>Release Date:</strong> <%= game.release_date %></p>
<p><strong>Price:</strong> <%= number_to_currency game.price %></p>
<p><strong>Quantity:</strong> <%= game.stock_quantity %></p>
<% if display_game_link %>
  <%= link_to 'Details', game %>
  <!-- <%= link_to 'Details', game_path(game) %> -->
  <!-- <%= link_to 'Details', game_path(id: game.id) %> -->
<% else %>
  <a href="/games/<%= game.id %>"></a>
<% end %>

app/views/games/index.html.erb
<h1>Games</h1>
<% @games.each do |game| %>
  <%= render partial: 'game',
             object: game,
             locals: { display_game_link: true } %>
<% end %>

app/views/games/search_results.html.erb
<h2>Search Results for "<%= params[:search_keywords] %>"</h2>
<% if @games.size.zero? %>
  <p>No products found.</p>
<% else %>
  <p><%= pluralize(@games.size, 'product') %> found.</p>
  <%= render partial: 'game',
             collection: @games,
             locals: { display_game_link: true } %>
<% end %>

app/views/games/show.html.erb
<%= render partial: 'game',
                    object: @game,
                    locals: { display_game_link: false } %>
<%= link_to 'Back', games_path %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<% @genres.each do |genre| %>
  <h2><%= genre.name %></h2>
  <%= link_to 'Details', genre %>
<% end %>

app/views/genres/show.html.erb
<h1>Genres</h1>
<% @genres.each do |genre| %>
  <h2><%= genre.name %></h2>
  <% genre.games.each do |game| %>
    <h3><%= game.title %></h3>
    <p><a href="/games/<%= game.id %>"><%= image_tag game.image_url %></a></p>
  <% end %>
<% end %>
<%= link_to 'Back', genres_path %>