config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
	resources :games,      only: [:index, :show]
  resources :developers, only: [:index, :show]
  resources :genres,     only: [:index, :show]
  resources :abouts,     only: [:index, :show]
  resources :contacts,   only: [:index, :show]
  
  get 'search_results' => 'games#search_results', as: 'search_results'
  
  get 'abouts/index'
  get 'contacts/index'

  get 'genres/index'
  get 'genres/show'

  get 'developers/index'
  get 'developers/show'

  get 'games/index'
  get 'games/show'

  get 'home/index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders,
           dependent: :destroy
  belongs_to :province

  validates :first_name,
            :last_name,
            :address,
            :city,
            :postal_code,
            :country,
            presence: true
  validates :credit_card_number,
            :credit_card_expiry_date,
            numericality: true
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games,
           dependent: :destroy

  validates :name,
            presence: true
  validates :name,
            uniqueness: true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :orders,
           dependent: :destroy
  belongs_to :developer
  belongs_to :genre

  validates :title,
            :stock_quantity,
            :price,
            presence: true
  validates :price,
            :stock_quantity,
            numericality: true
  validates :title,
            uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games,
           dependent: :destroy

  validates :name,
            presence: true
  validates :name,
            uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :games,
           dependent: :destroy
  belongs_to :customer

  validates :quantity,
            :total_price,
            numericality: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers,
           dependent: :destroy

  validates :name,
            presence: true
  validates :pst_rate,
            :gst_rate,
            :hst_rate,
            numericality: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index
    @about = About.first
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.order(:title)
  end

  def show
    @game = Game.find(params[:id])
  end

  def search_results
    wildcard_keywords = '%' + params[:search_keywords] + '%'
    genre_selection = params[:genre_id]

    if genre_selection.size.zero?
      @games = Game.where('title LIKE ?',
                          wildcard_keywords)
    else
      @games = Game.where('title LIKE ? AND genre_id = ?',
                          wildcard_keywords,
                          genre_selection)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @games = Game.order(:title)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/common/_header.html.erb
  <header>
    <nav>
      <%= link_to 'Home', root_path %> | 
      <%= link_to 'Games', games_path %> | 
      <%= link_to 'Developers', developers_path %> | 
      <%= link_to 'Genres', genres_path %> | 
      <%= link_to 'About', abouts_path %> | 
      <%= link_to 'Contact', contacts_path %>
    </nav>
    <%= form_tag search_results_path, method: :get do %>
      <%= text_field_tag :search_keywords %>
      <%= submit_tag 'Search' %>
      <%= select_tag :genre_id,
                     options_from_collection_for_select(Genre.all,
                                                        'id',
                                                        'name'),
                                                        prompt: 'All Genres' 
                                                        %>
    <% end %>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super Nintendo's Greatest Hits - Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <%= yield %>
  </body>
</html>